---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: ingress
  namespace: ingress
spec:
  releaseName: ingress-nginx
  chart:
    repository: https://kubernetes.github.io/ingress-nginx
    name: ingress-nginx
    version: 3.13.0
  values:
    controller:
      kind: DaemonSet	
      service:
        type: "NodePort"
        nodePorts:
          http: "31125"
          https: "30984"
      metrics:
        enabled: true
      stats:
        enabled: true
