---
apiVersion: helm.fluxcd.io/v1 
kind: HelmRelease
metadata:
  name: flux-web
  namespace: apps 
spec:
  releaseName: flux-web
  chart:
    git: https://github.com/flux-web/flux-web.git 
    path: chart/flux-web
    ref: master
  values:
    namespace: apps
    backend:
      tag: latest
      env:
        FLUX_URL: http://flux.fluxcd:3030
    frontend:
        env:
          API_EXTERNAL_URL: //flux.stackmasters.com/api/v1
          WS_URL: wss://flux.stackmasters.com/ws/v1
    ingress:
      enabled: true
      hosts:
        - host: flux.stackmasters.com
          paths: 
            - frontend: /
            - backend: /api
            - backend: /ws
