#sudo apt-get install python-docker
#sudo ln -sf /usr/bin/python3 /usr/bin/python to avoid the cannot import docker module error
- hosts: rke 

  tasks:
    - name: Prune everything (including non-dangling images)
      docker_prune:
        containers: yes
        images: yes
        images_filters:
          dangling: false
        networks: yes
        volumes: yes
        builder_cache: yes
