---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  releaseName: cert-manager
  chart:
    repository: https://charts.jetstack.io
    name: cert-manager
    version: v0.15.0-alpha.0
  values:
    installCRDs: true
    ingressShim:
      defaultIssuerName: "letsencrypt-prod"
      defaultIssuerKind: "ClusterIssuer"
    image:
      tag: "v0.15.0-alpha.0"
